// usuarios de prueba temporales
// todos tienen la clave 123456
export const usuariosMock = [
  {
    id: "u1",
    codigo: "EMP-001",
    nombre: "Ana",
    apellido: "Lopez",
    correo: "empleado@didelco.com",
    clave: "123456",
    rol: "EMPLEADO",
    puesto: "Auxiliar contable",
    empresa: "Didelco",
    departamento: "Contabilidad",
    jefeId: "u2",
    fechaIngreso: "2022-03-15",
    fotoUrl: null,
  },
  {
    id: "u2",
    codigo: "EMP-002",
    nombre: "Carlos",
    apellido: "Martinez",
    correo: "jefe@didelco.com",
    clave: "123456",
    rol: "JEFE",
    puesto: "Jefe de contabilidad",
    empresa: "Didelco",
    departamento: "Contabilidad",
    jefeId: null,
    fechaIngreso: "2018-07-01",
    fotoUrl: null,
  },
  {
    id: "u3",
    codigo: "EMP-003",
    nombre: "Sofia",
    apellido: "Rivas",
    correo: "analista@didelco.com",
    clave: "123456",
    rol: "ANALISTA",
    puesto: "Analista de nomina",
    empresa: "Didelco",
    departamento: "RRHH",
    jefeId: null,
    fechaIngreso: "2020-01-10",
    fotoUrl: null,
  },
  {
    id: "u4",
    codigo: "EMP-004",
    nombre: "Roberto",
    apellido: "Hernandez",
    correo: "gerente@didelco.com",
    clave: "123456",
    rol: "GERENTE",
    puesto: "Gerente general",
    empresa: "Didelco",
    departamento: "Administracion",
    jefeId: null,
    fechaIngreso: "2015-05-20",
    fotoUrl: null,
  },
  {
    id: "u5",
    codigo: "EMP-005",
    nombre: "Laura",
    apellido: "Gomez",
    correo: "rrhh@didelco.com",
    clave: "123456",
    rol: "RRHH",
    puesto: "Encargada de RRHH",
    empresa: "Didelco",
    departamento: "RRHH",
    jefeId: null,
    fechaIngreso: "2019-09-02",
    fotoUrl: null,
  },
];
